extends Node
class_name AttributeComponent

signal health_changed
signal no_health

var last_attacker = "NONE"
var killstreak := 0

@export var passive_heal_per_sec: float = 10.0
var _heal_timer: float = 0.0

var _time_since_last_damage: float = 0.0
const HEAL_DELAY := 5.0

@export var starting_health := 100.0

@export var health: float = 100.0:
	set(value):
		health = value
		health_changed.emit()
		if health <= 0.0:
			no_health.emit()


func reset_health():
	health = starting_health


func apply_health_delta(delta: float, changer: String, changee: String, is_headshot: bool = false, falloff_mult: float = 1.0):

	var old_health := health
	var new_health :float = clamp(old_health + delta, 0.0, starting_health)
	var applied_delta := new_health - old_health

	if is_zero_approx(applied_delta):
		return

	pass  # health change print removed



	var changer_node = GameManager.find_player(changer)
	if applied_delta < 0:
		_time_since_last_damage = 0.0

		if changee == changer:
			Leaderboard.request_add_self_damage(changer, applied_delta)
		else:
			Leaderboard.request_add_damage(changer, applied_delta)
			if not changer_node.is_bot:
				if is_headshot:
					changer_node.weapon_controller.play_crit_sound.rpc_id(changer.to_int())
				else:
					changer_node.weapon_controller.play_hit_sound.rpc_id(changer.to_int())
				changer_node.damage_number_manager._receive_damage_number.rpc_id(changer.to_int(), changee, applied_delta, is_headshot, falloff_mult)
		last_attacker = changer
	else:
		if changee == changer:
			Leaderboard.request_add_self_heal(changer, applied_delta)
		else:
			Leaderboard.request_add_heal_other(changer, applied_delta)
			if not changer_node.is_bot:
				changer_node.weapon_controller.play_hit_heal_sound.rpc_id(changer.to_int())
				changer_node.damage_number_manager._receive_damage_number.rpc_id(changer.to_int(), changee, applied_delta)


	if old_health > 0.0 and new_health <= 0.0:
		if changee != changer:
			# Resolve weapon info for the kill feed.
			var weapon_name: String = ""
			var killfeed_icon_path: String = ""
			if changer_node:
				var wc: WeaponController = changer_node.weapon_controller
				if wc:
					var weapons: Array[Weapon] = wc.get_weapons()
					if not weapons.is_empty():
						var idx: int = wc.current_weapon_index
						if idx >= 0 and idx < weapons.size():
							weapon_name = weapons[idx].display_name
							# Pre-rendered kill-feed icon (generated by
							# weapon/killfeed_icon_generator.gd).  Falls
							# back to text-only if no icon is assigned.
							if weapons[idx].killfeed_icon:
								killfeed_icon_path = weapons[idx].killfeed_icon.resource_path

			Leaderboard.request_add_kill(changer, changee, weapon_name, killfeed_icon_path)
			Leaderboard.request_add_death(changee)
			# Heal on kill: restore HP to the killer based on their character.
			var killer: Player = GameManager.find_player(changer)
			if killer and killer._character:
				var hok: float = killer._character.heal_on_kill
				if hok > 0.0:
					killer.change_health(hok, changer)

	if abs(applied_delta) > 0.0001:
		health = new_health


func reset():
	reset_health()
	last_attacker = "NONE"
	_time_since_last_damage = 0.0
	_heal_timer = 0.0  # ← add this

func _process(delta: float) -> void:
	# Character regen overrides base values when set (non-null character).
	var heal_rate: float = passive_heal_per_sec
	var heal_delay: float = HEAL_DELAY
	var p: Player = get_parent() as Player
	if p and p._character:
		heal_rate = p._character.regen_per_sec
		heal_delay = p._character.regen_delay

	if heal_rate < 0.0:
		# Negative regen = damage over time.  Applied directly, bypasses
		# the heal-delay gate and can kill the player (setter emits no_health).
		health = health + heal_rate * delta
		return

	_time_since_last_damage += delta
	if health <= 0.0 or health >= starting_health:
		_heal_timer = 0.0
		return
	if _time_since_last_damage < heal_delay:
		return
	apply_health_delta(heal_rate * delta, get_parent().name, get_parent().name)
