extends Node
class_name AttributeComponent

signal health_changed
signal no_health

var last_attacker = "NONE"
## Direction of the last damaging hit (away from the attacker), used to knock the
## death ragdoll backward.  Overwritten on every hit, so it holds the killing blow.
var last_hit_direction: Vector3 = Vector3.ZERO
var killstreak := 0

## Last *enemy* who damaged this player, credited for environmental kills
## (fall damage, hazards).  Expires after ENEMY_ATTACKER_EXPIRY seconds.
var last_enemy_attacker = "NONE"
var _enemy_attacker_expiry: Timer

@export var passive_heal_per_sec: float = 10.0

var _time_since_last_damage: float = 0.0
const HEAL_DELAY := 5.0
const ENEMY_ATTACKER_EXPIRY := 30.0

@export var starting_health := 100.0

@export var health: float = 100.0:
	set(value):
		health = value
		health_changed.emit()
		if health <= 0.0:
			no_health.emit()


func reset_health():
	health = starting_health


func _ready() -> void:
	_enemy_attacker_expiry = Timer.new()
	_enemy_attacker_expiry.name = "EnemyAttackerExpiryTimer"
	_enemy_attacker_expiry.wait_time = ENEMY_ATTACKER_EXPIRY
	_enemy_attacker_expiry.one_shot = true
	_enemy_attacker_expiry.timeout.connect(_on_enemy_attacker_expired)
	add_child(_enemy_attacker_expiry)


func _on_enemy_attacker_expired() -> void:
	last_enemy_attacker = "NONE"


func apply_health_delta(delta: float, changer: String, changee: String, is_headshot: bool = false, falloff_mult: float = 1.0, is_backshot: bool = false):

	var old_health := health
	var new_health :float = clamp(old_health + delta, 0.0, starting_health)
	var applied_delta := new_health - old_health

	if is_zero_approx(applied_delta):
		return

	pass  # health change print removed



	var changer_node = GameManager.find_player(changer)
	if applied_delta < 0:
		_time_since_last_damage = 0.0

		if changee == changer:
			Leaderboard.request_add_self_damage(changer, applied_delta)
		else:
			Leaderboard.request_add_damage(changer, applied_delta)
			if not changer_node.is_bot:
				if is_headshot:
					changer_node.weapon_controller.play_crit_sound.rpc_id(changer.to_int())
				else:
					changer_node.weapon_controller.play_hit_sound.rpc_id(changer.to_int())
				changer_node.damage_number_manager._receive_damage_number.rpc_id(changer.to_int(), changee, applied_delta, is_headshot, falloff_mult, is_backshot)
		last_attacker = changer
		if changer_node != null and changer_node != get_parent():
			last_hit_direction = ((get_parent() as Node3D).global_position - changer_node.global_position).normalized()
		if _is_enemy_attacker(changer):
			last_enemy_attacker = changer
			if _enemy_attacker_expiry:
				_enemy_attacker_expiry.start()
	else:
		if changee == changer:
			Leaderboard.request_add_self_heal(changer, applied_delta)
		else:
			Leaderboard.request_add_heal_other(changer, applied_delta)
			if not changer_node.is_bot:
				changer_node.weapon_controller.play_hit_heal_sound.rpc_id(changer.to_int())
				changer_node.damage_number_manager._receive_damage_number.rpc_id(changer.to_int(), changee, applied_delta)


	if old_health > 0.0 and new_health <= 0.0:
		if changee != changer:
			# Resolve weapon info for the kill feed.
			var weapon_name: String = ""
			var killfeed_icon_path: String = ""
			if changer_node:
				var wc: WeaponController = changer_node.weapon_controller
				if wc:
					var weapons: Array[Weapon] = wc.get_weapons()
					if not weapons.is_empty():
						var idx: int = wc.current_weapon_index
						if idx >= 0 and idx < weapons.size():
							weapon_name = weapons[idx].display_name
							# Pre-rendered kill-feed icon (generated by
							# weapon/killfeed_icon_generator.gd).  Falls
							# back to text-only if no icon is assigned.
							if weapons[idx].killfeed_icon:
								killfeed_icon_path = weapons[idx].killfeed_icon.resource_path

			Leaderboard.request_add_kill(changer, changee, weapon_name, killfeed_icon_path, is_headshot, is_backshot)
			Leaderboard.request_add_death(changee)
			# Heal on kill: restore HP to the killer based on their character.
			var killer: Player = GameManager.find_player(changer)
			if killer and killer._character:
				var hok: float = killer._character.heal_on_kill
				if hok > 0.0:
					killer.change_health(hok, changer)

	if abs(applied_delta) > 0.0001:
		health = new_health


## True when [param changer] is on an opposing team (or everyone, in FFA).
func _is_enemy_attacker(changer: String) -> bool:
	if changer == get_parent().name:
		return false
	var changer_p: Player = GameManager.find_player(changer)
	var self_p: Player = get_parent() as Player
	if changer_p == null or self_p == null:
		return false
	if self_p.team == Player.Team.FFA:
		return true
	return changer_p.team != self_p.team


## Apply damage from the environment (fall, hazards, etc.).  Credits the last
## enemy who damaged this player (if not expired) for the kill.
func apply_environmental_damage(damage: float) -> void:
	if damage <= 0.0:
		return
	var changer: String = get_parent().name
	if last_enemy_attacker != "NONE" and GameManager.find_player(last_enemy_attacker) != null:
		changer = last_enemy_attacker
	apply_health_delta(-damage, changer, get_parent().name)


func reset():
	reset_health()
	last_attacker = "NONE"
	last_hit_direction = Vector3.ZERO
	last_enemy_attacker = "NONE"
	if _enemy_attacker_expiry:
		_enemy_attacker_expiry.stop()
	_time_since_last_damage = 0.0

func _process(delta: float) -> void:
	# Character regen overrides base values when set (non-null character).
	var heal_rate: float = passive_heal_per_sec
	var heal_delay: float = HEAL_DELAY
	var p: Player = get_parent() as Player
	if p and p._character:
		heal_rate = p._character.regen_per_sec
		heal_delay = p._character.regen_delay

	if heal_rate < 0.0:
		# Negative regen = damage over time.  Applied directly, bypasses
		# the heal-delay gate and can kill the player (setter emits no_health).
		health = health + heal_rate * delta
		return

	_time_since_last_damage += delta
	if health <= 0.0 or health >= starting_health:
		return
	if _time_since_last_damage < heal_delay:
		return
	apply_health_delta(heal_rate * delta, get_parent().name, get_parent().name)
